import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import localFont from "next/font/local"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const kingsguard = localFont({
  src: [
    {
      path: "./fonts/KingsguardCalligraphyPERSONA-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/KingsguardCalligraphyPERSONA-Regular.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-kingsguard",
  display: "swap",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${kingsguard.variable}
          antialiased
       
        `}
      >
        {children}
      </body>
    </html>
  )
}
